server:
  port: 8099

spring:
  application:
    name: springcloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: springcloud-feign-order
    api-b:
      path: /api-b/**
      serviceId: springcloud-ribbin-user