server:
  port: 8090
spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiangtaoyun/springcloud-zhaoping.git
          search-paths: /
          username: jiangtaoyun
          password: l13467156639
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
